### ISSUE TITLE
Cannot set position programatically

### ISSUE THREAD

**Issue by raphaelweber** [lokku/jquery-nstslider#30]
In combination with jQuery 3.1.0 I get the following error when trying to use `set_position`:

> Uncaught Error: cannot compare s: [object Object] with a[145]. a is: [...] 

Usage:
`$('.nstSlider').nstSlider('set_position', {min:100, max:5000});`

**Comment by darksmo** [comment]
Hello,

is that because you are not using positional arguments? I have updated the README in this commit: https://github.com/lokku/jquery-nstslider/commit/6bccc14e3c8e435673c126a588c9a6e53b4bd032 .

Please use positional arguments instead of an object as per documentation, and reopen this issue if necessary.
